name: SkJadePlus
version: '${version}'
description: "§7Enhance §eSkript §7with this add-on and use custom syntax! §c❤"
authors: [Ankoki, HamzaQaz]
website: 'https://www.github.com/HamzaQaz/SkJadePlus'
api-version: '1.21'
main: com.ankoki.skjadeplus.SkJadePlus
commands:
  skjadeplus:
    description: Shows the version of SkJadePlus that is currently being run.
    aliases: [skjade]
depend:
  - Skript
softdepend:
  - HolographicDisplays
  - Citizens
  - Elementals
  - ProtocolLib